---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Main branch commit build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/

specfile_path: conmon-rs.spec

srpm_build_deps:
  - cargo
  - make
  - rpkg

actions:
  post-upstream-clone:
    - "rpkg spec --outdir ./"
  fix-spec-file:
    - "bash .packit.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    # keep in sync with https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next
    enable_net: true
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
      - centos-stream+epel-next-8-x86_64
      - centos-stream+epel-next-8-aarch64
      - centos-stream+epel-next-9-x86_64
      - centos-stream+epel-next-9-aarch64
    additional_repos:
      - "copr://rhcontainerbot/podman-next"

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true
