[package]
name = "conmon-rs"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the ConmonServer gRPC server
name = "conmon-server"
path = "src/server.rs"

[[bin]]
name = "conmon-client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.45"
clap = { git = "https://github.com/clap-rs/clap", features = ["wrap_help"] }
env_logger = "0.9.0"
getset = "0.1.1"
log = { version = "0.4.14", features = ["serde", "std"] }
prost = "0.9.0"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.13.0", features = ["macros", "rt"] }
tonic = "0.6.1"

[build-dependencies]
tonic-build = "0.6.0"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
