[workspace]
members = [
	"conmon-rs/common",
	"conmon-rs/client",
	"conmon-rs/server",
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1

[dev-dependencies]
tempfile = "3.2.0"
codegen-units = 1
