[package]
name = "conmon-common"
# Version listed below is also used by .packit.sh
version = "0.6.3"
edition = "2021"

[dependencies]
capnp = "0.19.3"

[build-dependencies]
capnp = "0.19.3"
capnpc = "0.19.0"
