[package]
name = "conmon-common"
# Version listed below is also used by .packit.sh
version = "0.5.0"
edition = "2018"

[dependencies]
capnp = "0.14.11"

[build-dependencies]
capnp = "0.14.11"
capnpc = "0.14.9"
