[package]
name = "conmonrs-cli"
version = "0.6.1"
edition = "2021"

[dependencies]
capnp = "0.19.3"
capnp-rpc = "0.19.0"
conmon-common = { path = "../common" }
futures = "0.3.30"
log = { version = "0.4.21", features = ["serde", "std"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["fs", "macros", "net", "process", "rt", "signal", "time"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
